# ctrl+/ to comment-uncomment
# All the commented configuration is moved to schools.yml in the config-server service to Externalize configuration
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8070
spring:
  application:
    name: schools
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/schools
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    #application:
    #  config:
    #    students-url: http://localhost:8222/api/v1/students # School service calls student through gateway
    #    students-url: http://localhost:8090/api/v1/students school micro-service calls Student directly